spring.config.import=optional:file:.env[.properties]
spring.application.name=hairo-server
server.port=${PORT:8080}
discord.token=${DISCORD_TOKEN}
discord.channelId=1367323226107023471
vertesia.token=${VERTESIA_TOKEN}
github.token=${GITHUB_TOKEN}
discord.channel.coc=1367323226107023471
discord.channel.maintainers=1367309156402466960
