spring.config.import=optional:file:.env[.properties]
spring.application.name=hairo-server
server.port=${PORT:8080}
discord.token=${DISCORD_TOKEN}
vertesia.token=${VERTESIA_TOKEN}
github.token=${GITHUB_TOKEN}
discord.channel.coc=1367581576770355274
discord.channel.maintainers=1367540029022404678
discord.channel.issues=1367575143743750295
